In [11]:
import pandas as pd
import numpy as np

from pymongo import MongoClient
from dotenv import load_dotenv
import os

In [12]:
load_dotenv()

client = MongoClient(os.getenv("MONGODB_URI"))

db = client["aqi_predictor"]

collection = db["aqi_features"]

df = pd.DataFrame(list(collection.find()))

In [13]:
if "_id" in df.columns:
    df.drop(columns="_id", inplace=True)

df["timestamp"] = pd.to_datetime(df["timestamp"])

df = df.sort_values("timestamp")

df.reset_index(drop=True, inplace=True)

print(df.shape)

df.head()

(8496, 18)

,city,timestamp,hour,day,month,day_of_week,aqi,aqi_change_rate,pm25,pm10,o3,no2,so2,co,temperature,humidity,pressure,wind_speed
0,karachi,2025-08-05 08:00:00+00:00,8,5,8,1,48,0.0,11.49,45.48,44.97,0.05,0.31,76.93,29.8,70,1002.5,20.9
1,karachi,2025-08-05 09:00:00+00:00,9,5,8,1,47,-1.0,11.23,44.70,44.90,0.05,0.31,76.80,29.5,71,1002.2,20.0
2,karachi,2025-08-05 10:00:00+00:00,10,5,8,1,46,-1.0,10.95,44.54,44.71,0.05,0.31,76.69,29.3,72,1002.0,19.5
3,karachi,2025-08-05 11:00:00+00:00,11,5,8,1,44,-2.0,10.50,44.20,44.39,0.06,0.31,77.06,29.2,72,1001.6,19.9
4,karachi,2025-08-05 12:00:00+00:00,12,5,8,1,43,-1.0,10.21,44.55,43.94,0.06,0.31,77.63,28.9,73,1001.4,19.5

In [14]:
# AQI lag features
df["aqi_lag_1"] = df["aqi"].shift(1)
df["aqi_lag_3"] = df["aqi"].shift(3)
df["aqi_lag_6"] = df["aqi"].shift(6)
df["aqi_lag_12"] = df["aqi"].shift(12)
df["aqi_lag_24"] = df["aqi"].shift(24)

# PM2.5 lag features
df["pm25_lag_1"] = df["pm25"].shift(1)
df["pm25_lag_6"] = df["pm25"].shift(6)
df["pm25_lag_24"] = df["pm25"].shift(24)

df.head(30)

,city,timestamp,hour,day,month,day_of_week,aqi,aqi_change_rate,pm25,pm10,...,pressure,wind_speed,aqi_lag_1,aqi_lag_3,aqi_lag_6,aqi_lag_12,aqi_lag_24,pm25_lag_1,pm25_lag_6,pm25_lag_24
0,karachi,2025-08-05 08:00:00+00:00,8,5,8,1,48,0.0,11.49,45.48,...,1002.5,20.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,karachi,2025-08-05 09:00:00+00:00,9,5,8,1,47,-1.0,11.23,44.70,...,1002.2,20.0,48.0,NaN,NaN,NaN,NaN,11.49,NaN,NaN
2,karachi,2025-08-05 10:00:00+00:00,10,5,8,1,46,-1.0,10.95,44.54,...,1002.0,19.5,47.0,NaN,NaN,NaN,NaN,11.23,NaN,NaN
3,karachi,2025-08-05 11:00:00+00:00,11,5,8,1,44,-2.0,10.50,44.20,...,1001.6,19.9,46.0,48.0,NaN,NaN,NaN,10.95,NaN,NaN
4,karachi,2025-08-05 12:00:00+00:00,12,5,8,1,43,-1.0,10.21,44.55,...,1001.4,19.5,44.0,47.0,NaN,NaN,NaN,10.50,NaN,NaN
5,karachi,2025-08-05 13:00:00+00:00,13,5,8,1,42,-1.0,10.13,42.87,...,1001.6,16.2,43.0,46.0,NaN,NaN,NaN,10.21,NaN,NaN
6,karachi,2025-08-05 14:00:00+00:00,14,5,8,1,43,1.0,10.26,40.95,...,1001.8,14.7,42.0,44.0,48.0,NaN,NaN,10.13,11.49,NaN
7,karachi,2025-08-05 15:00:00+00:00,15,5,8,1,44,1.0,10.64,41.22,...,1002.2,14.5,43.0,43.0,47.0,NaN,NaN,10.26,11.23,NaN
8,karachi,2025-08-05 16:00:00+00:00,16,5,8,1,46,2.0,11.09,44.47,...,1002.8,15.6,44.0,42.0,46.0,NaN,NaN,10.64,10.95,NaN
9,karachi,2025-08-05 17:00:00+00:00,17,5,8,1,48,2.0,11.44,48.09,...,1003.5,14.8,46.0,43.0,44.0,NaN,NaN,11.09,10.50,NaN
10,karachi,2025-08-05 18:00:00+00:00,18,5,8,1,49,1.0,11.72,50.02,...,1003.6,14.6,48.0,44.0,43.0,NaN,NaN,11.44,10.21,NaN
11,karachi,2025-08-05 19:00:00+00:00,19,5,8,1,50,1.0,11.97,50.03,...,1003.4,14.6,49.0,46.0,42.0,NaN,NaN,11.72,10.13,NaN
12,karachi,2025-08-05 20:00:00+00:00,20,5,8,1,51,1.0,12.24,49.43,...,1003.1,14.9,50.0,48.0,43.0,48.0,NaN,11.97,10.26,NaN
13,karachi,2025-08-05 21:00:00+00:00,21,5,8,1,52,1.0,12.57,49.92,...,1002.4,15.8,51.0,49.0,44.0,47.0,NaN,12.24,10.64,NaN
14,karachi,2025-08-05 22:00:00+00:00,22,5,8,1,53,1.0,12.90,50.84,...,1002.3,15.9,52.0,50.0,46.0,46.0,NaN,12.57,11.09,NaN
15,karachi,2025-08-05 23:00:00+00:00,23,5,8,1,54,1.0,13.36,55.41,...,1002.1,15.3,53.0,51.0,48.0,44.0,NaN,12.90,11.44,NaN
16,karachi,2025-08-06 00:00:00+00:00,0,6,8,2,54,0.0,13.74,59.63,...,1002.4,14.2,54.0,52.0,49.0,43.0,NaN,13.36,11.72,NaN
17,karachi,2025-08-06 01:00:00+00:00,1,6,8,2,55,1.0,13.83,60.66,...,1002.2,13.2,54.0,53.0,50.0,42.0,NaN,13.74,11.97,NaN
18,karachi,2025-08-06 02:00:00+00:00,2,6,8,2,54,-1.0,13.56,58.45,...,1002.8,14.0,55.0,54.0,51.0,43.0,NaN,13.83,12.24,NaN
19,karachi,2025-08-06 03:00:00+00:00,3,6,8,2,53,-1.0,13.07,55.35,...,1003.2,16.2,54.0,54.0,52.0,44.0,NaN,13.56,12.57,NaN
20,karachi,2025-08-06 04:00:00+00:00,4,6,8,2,52,-1.0,12.55,53.89,...,1003.6,18.4,53.0,55.0,53.0,46.0,NaN,13.07,12.90,NaN
21,karachi,2025-08-06 05:00:00+00:00,5,6,8,2,51,-1.0,12.15,53.38,...,1003.9,18.8,52.0,54.0,54.0,48.0,NaN,12.55,13.36,NaN
22,karachi,2025-08-06 06:00:00+00:00,6,6,8,2,49,-2.0,11.78,52.45,...,1003.8,19.6,51.0,53.0,54.0,49.0,NaN,12.15,13.74,NaN
23,karachi,2025-08-06 07:00:00+00:00,7,6,8,2,47,-2.0,11.33,49.07,...,1003.7,18.8,49.0,52.0,55.0,50.0,NaN,11.78,13.83,NaN
24,karachi,2025-08-06 08:00:00+00:00,8,6,8,2,45,-2.0,10.78,44.28,...,1003.2,18.1,47.0,51.0,54.0,51.0,48.0,11.33,13.56,11.49
25,karachi,2025-08-06 09:00:00+00:00,9,6,8,2,43,-2.0,10.31,40.05,...,1002.4,18.3,45.0,49.0,53.0,52.0,47.0,10.78,13.07,11.23
26,karachi,2025-08-06 10:00:00+00:00,10,6,8,2,42,-1.0,10.09,37.30,...,1002.1,18.3,43.0,47.0,52.0,53.0,46.0,10.31,12.55,10.95
27,karachi,2025-08-06 11:00:00+00:00,11,6,8,2,42,0.0,10.14,35.84,...,1001.9,18.7,42.0,45.0,51.0,54.0,44.0,10.09,12.15,10.50
28,karachi,2025-08-06 12:00:00+00:00,12,6,8,2,43,1.0,10.25,34.89,...,1001.9,18.4,42.0,43.0,49.0,54.0,43.0,10.14,11.78,10.21
29,karachi,2025-08-06 13:00:00+00:00,13,6,8,2,43,0.0,10.33,34.50,...,1002.4,17.4,43.0,42.0,47.0,55.0,42.0,10.25,11.33,10.13

In [15]:
# AQI rolling mean
df["aqi_roll_mean_6"] = df["aqi"].rolling(6).mean()

df["aqi_roll_mean_12"] = df["aqi"].rolling(12).mean()

df["aqi_roll_mean_24"] = df["aqi"].rolling(24).mean()

# AQI rolling standard deviation
df["aqi_roll_std_24"] = df["aqi"].rolling(24).std()

df.head(30)

,city,timestamp,hour,day,month,day_of_week,aqi,aqi_change_rate,pm25,pm10,...,aqi_lag_6,aqi_lag_12,aqi_lag_24,pm25_lag_1,pm25_lag_6,pm25_lag_24,aqi_roll_mean_6,aqi_roll_mean_12,aqi_roll_mean_24,aqi_roll_std_24
0,karachi,2025-08-05 08:00:00+00:00,8,5,8,1,48,0.0,11.49,45.48,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,karachi,2025-08-05 09:00:00+00:00,9,5,8,1,47,-1.0,11.23,44.70,...,NaN,NaN,NaN,11.49,NaN,NaN,NaN,NaN,NaN,NaN
2,karachi,2025-08-05 10:00:00+00:00,10,5,8,1,46,-1.0,10.95,44.54,...,NaN,NaN,NaN,11.23,NaN,NaN,NaN,NaN,NaN,NaN
3,karachi,2025-08-05 11:00:00+00:00,11,5,8,1,44,-2.0,10.50,44.20,...,NaN,NaN,NaN,10.95,NaN,NaN,NaN,NaN,NaN,NaN
4,karachi,2025-08-05 12:00:00+00:00,12,5,8,1,43,-1.0,10.21,44.55,...,NaN,NaN,NaN,10.50,NaN,NaN,NaN,NaN,NaN,NaN
5,karachi,2025-08-05 13:00:00+00:00,13,5,8,1,42,-1.0,10.13,42.87,...,NaN,NaN,NaN,10.21,NaN,NaN,45.000000,NaN,NaN,NaN
6,karachi,2025-08-05 14:00:00+00:00,14,5,8,1,43,1.0,10.26,40.95,...,48.0,NaN,NaN,10.13,11.49,NaN,44.166667,NaN,NaN,NaN
7,karachi,2025-08-05 15:00:00+00:00,15,5,8,1,44,1.0,10.64,41.22,...,47.0,NaN,NaN,10.26,11.23,NaN,43.666667,NaN,NaN,NaN
8,karachi,2025-08-05 16:00:00+00:00,16,5,8,1,46,2.0,11.09,44.47,...,46.0,NaN,NaN,10.64,10.95,NaN,43.666667,NaN,NaN,NaN
9,karachi,2025-08-05 17:00:00+00:00,17,5,8,1,48,2.0,11.44,48.09,...,44.0,NaN,NaN,11.09,10.50,NaN,44.333333,NaN,NaN,NaN
10,karachi,2025-08-05 18:00:00+00:00,18,5,8,1,49,1.0,11.72,50.02,...,43.0,NaN,NaN,11.44,10.21,NaN,45.333333,NaN,NaN,NaN
11,karachi,2025-08-05 19:00:00+00:00,19,5,8,1,50,1.0,11.97,50.03,...,42.0,NaN,NaN,11.72,10.13,NaN,46.666667,45.833333,NaN,NaN
12,karachi,2025-08-05 20:00:00+00:00,20,5,8,1,51,1.0,12.24,49.43,...,43.0,48.0,NaN,11.97,10.26,NaN,48.000000,46.083333,NaN,NaN
13,karachi,2025-08-05 21:00:00+00:00,21,5,8,1,52,1.0,12.57,49.92,...,44.0,47.0,NaN,12.24,10.64,NaN,49.333333,46.500000,NaN,NaN
14,karachi,2025-08-05 22:00:00+00:00,22,5,8,1,53,1.0,12.90,50.84,...,46.0,46.0,NaN,12.57,11.09,NaN,50.500000,47.083333,NaN,NaN
15,karachi,2025-08-05 23:00:00+00:00,23,5,8,1,54,1.0,13.36,55.41,...,48.0,44.0,NaN,12.90,11.44,NaN,51.500000,47.916667,NaN,NaN
16,karachi,2025-08-06 00:00:00+00:00,0,6,8,2,54,0.0,13.74,59.63,...,49.0,43.0,NaN,13.36,11.72,NaN,52.333333,48.833333,NaN,NaN
17,karachi,2025-08-06 01:00:00+00:00,1,6,8,2,55,1.0,13.83,60.66,...,50.0,42.0,NaN,13.74,11.97,NaN,53.166667,49.916667,NaN,NaN
18,karachi,2025-08-06 02:00:00+00:00,2,6,8,2,54,-1.0,13.56,58.45,...,51.0,43.0,NaN,13.83,12.24,NaN,53.666667,50.833333,NaN,NaN
19,karachi,2025-08-06 03:00:00+00:00,3,6,8,2,53,-1.0,13.07,55.35,...,52.0,44.0,NaN,13.56,12.57,NaN,53.833333,51.583333,NaN,NaN
20,karachi,2025-08-06 04:00:00+00:00,4,6,8,2,52,-1.0,12.55,53.89,...,53.0,46.0,NaN,13.07,12.90,NaN,53.666667,52.083333,NaN,NaN
21,karachi,2025-08-06 05:00:00+00:00,5,6,8,2,51,-1.0,12.15,53.38,...,54.0,48.0,NaN,12.55,13.36,NaN,53.166667,52.333333,NaN,NaN
22,karachi,2025-08-06 06:00:00+00:00,6,6,8,2,49,-2.0,11.78,52.45,...,54.0,49.0,NaN,12.15,13.74,NaN,52.333333,52.333333,NaN,NaN
23,karachi,2025-08-06 07:00:00+00:00,7,6,8,2,47,-2.0,11.33,49.07,...,55.0,50.0,NaN,11.78,13.83,NaN,51.000000,52.083333,48.958333,4.005205
24,karachi,2025-08-06 08:00:00+00:00,8,6,8,2,45,-2.0,10.78,44.28,...,54.0,51.0,48.0,11.33,13.56,11.49,49.500000,51.583333,48.833333,4.082483
25,karachi,2025-08-06 09:00:00+00:00,9,6,8,2,43,-2.0,10.31,40.05,...,53.0,52.0,47.0,10.78,13.07,11.23,47.833333,50.833333,48.666667,4.239223
26,karachi,2025-08-06 10:00:00+00:00,10,6,8,2,42,-1.0,10.09,37.30,...,52.0,53.0,46.0,10.31,12.55,10.95,46.166667,49.916667,48.500000,4.423259
27,karachi,2025-08-06 11:00:00+00:00,11,6,8,2,42,0.0,10.14,35.84,...,51.0,54.0,44.0,10.09,12.15,10.50,44.666667,48.916667,48.416667,4.529293
28,karachi,2025-08-06 12:00:00+00:00,12,6,8,2,43,1.0,10.25,34.89,...,49.0,54.0,43.0,10.14,11.78,10.21,43.666667,48.000000,48.416667,4.529293
29,karachi,2025-08-06 13:00:00+00:00,13,6,8,2,43,0.0,10.33,34.50,...,47.0,55.0,42.0,10.25,11.33,10.13,43.000000,47.000000,48.458333,4.471933

In [16]:
FORECAST_HOURS = 72

df["target_aqi"] = [
    df["aqi"].iloc[i + 1:i + 1 + FORECAST_HOURS].mean()
    if i + FORECAST_HOURS < len(df)
    else np.nan
    for i in range(len(df))
]

In [17]:
df = df.dropna()

df.reset_index(drop=True, inplace=True)

print(df.shape)

(8400, 31)

In [18]:
FEATURES = [

    # Calendar
    "hour",
    "day",
    "month",
    "day_of_week",

    # Pollutants
    "pm25",
    "pm10",
    "o3",
    "no2",
    "so2",
    "co",

    # Weather
    "temperature",
    "humidity",
    "pressure",
    "wind_speed",

    # AQI lag
    "aqi_lag_1",
    "aqi_lag_3",
    "aqi_lag_6",
    "aqi_lag_12",
    "aqi_lag_24",

    # PM2.5 lag
    "pm25_lag_1",
    "pm25_lag_6",
    "pm25_lag_24",

    # Rolling
    "aqi_roll_mean_6",
    "aqi_roll_mean_12",
    "aqi_roll_mean_24",
    "aqi_roll_std_24",
]

In [19]:
X = df[FEATURES]

y = df["target_aqi"]

print(X.shape)

print(y.shape)

(8400, 26)
(8400,)

In [20]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    shuffle=False,
)

print("Training")

print(X_train.shape)

print(y_train.shape)

print()

print("Testing")

print(X_test.shape)

print(y_test.shape)

Training
(6720, 26)
(6720,)

Testing
(1680, 26)
(1680,)

In [21]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score,
)

import numpy as np
import pandas as pd

In [22]:
lr_model = LinearRegression()

lr_model.fit(X_train, y_train)

print("Linear Regression trained successfully.")

Linear Regression trained successfully.

In [23]:
lr_predictions = lr_model.predict(X_test)

lr_mae = mean_absolute_error(y_test, lr_predictions)
lr_rmse = np.sqrt(mean_squared_error(y_test, lr_predictions))
lr_r2 = r2_score(y_test, lr_predictions)

print(f"MAE  : {lr_mae:.2f}")
print(f"RMSE : {lr_rmse:.2f}")
print(f"R²   : {lr_r2:.4f}")

MAE  : 13.28
RMSE : 16.94
R²   : -0.0933

In [24]:
rf_model = RandomForestRegressor(
    n_estimators=300,
    max_depth=20,
    min_samples_split=5,
    min_samples_leaf=2,
    random_state=42,
    n_jobs=-1,
)

rf_model.fit(X_train, y_train)

print("Random Forest trained successfully.")

Random Forest trained successfully.

In [25]:
rf_predictions = rf_model.predict(X_test)

rf_mae = mean_absolute_error(y_test, rf_predictions)
rf_rmse = np.sqrt(mean_squared_error(y_test, rf_predictions))
rf_r2 = r2_score(y_test, rf_predictions)

print(f"MAE  : {rf_mae:.2f}")
print(f"RMSE : {rf_rmse:.2f}")
print(f"R²   : {rf_r2:.4f}")

MAE  : 9.63
RMSE : 12.67
R²   : 0.3885

In [26]:
comparison = pd.DataFrame({
    "Model": [
        "Linear Regression",
        "Random Forest"
    ],
    "MAE": [
        lr_mae,
        rf_mae
    ],
    "RMSE": [
        lr_rmse,
        rf_rmse
    ],
    "R²": [
        lr_r2,
        rf_r2
    ]
})

comparison = comparison.sort_values(
    by="RMSE",
    ascending=True
).reset_index(drop=True)

comparison

               Model        MAE       RMSE        R²
0      Random Forest   9.634611  12.665019  0.388539
1  Linear Regression  13.276649  16.935594 -0.093346

In [27]:
importance = pd.DataFrame({
    "Feature": FEATURES,
    "Importance": rf_model.feature_importances_
})

importance = importance.sort_values(
    by="Importance",
    ascending=False
)

importance

             Feature  Importance
9                 co    0.515695
6                 o3    0.082756
2              month    0.068373
4               pm25    0.057605
5               pm10    0.051015
1                day    0.048006
24  aqi_roll_mean_24    0.034652
12          pressure    0.023258
3        day_of_week    0.021101
21       pm25_lag_24    0.016754
25   aqi_roll_std_24    0.011771
8                so2    0.011351
23  aqi_roll_mean_12    0.010596
7                no2    0.010462
18        aqi_lag_24    0.006660
22   aqi_roll_mean_6    0.005761
17        aqi_lag_12    0.005335
19        pm25_lag_1    0.004451
13        wind_speed    0.003788
11          humidity    0.002300
10       temperature    0.002031
20        pm25_lag_6    0.001684
15         aqi_lag_3    0.001496
16         aqi_lag_6    0.001410
14         aqi_lag_1    0.001042
0               hour    0.000649

In [28]:
from sklearn.linear_model import Ridge

In [29]:
ridge_model = Ridge(
    alpha=1.0,
    random_state=42,
)

ridge_model.fit(X_train, y_train)

print("Ridge Regression trained successfully.")

Ridge Regression trained successfully.

In [30]:
ridge_predictions = ridge_model.predict(X_test)

ridge_predictions[:10]

array([60.32474737, 59.09641761, 57.4396565 , 56.5606779 , 55.05928817,
       54.17585893, 53.46948252, 53.78601296, 55.05007855, 56.15188006])

In [31]:
ridge_mae = mean_absolute_error(y_test, ridge_predictions)

ridge_rmse = np.sqrt(mean_squared_error(y_test, ridge_predictions))

ridge_r2 = r2_score(y_test, ridge_predictions)

print(f"MAE  : {ridge_mae:.2f}")
print(f"RMSE : {ridge_rmse:.2f}")
print(f"R²   : {ridge_r2:.4f}")

MAE  : 13.28
RMSE : 16.94
R²   : -0.0933

In [32]:
ridge_importance = pd.DataFrame({
    "Feature": FEATURES,
    "Coefficient": ridge_model.coef_
})

ridge_importance["Absolute"] = ridge_importance["Coefficient"].abs()

ridge_importance = ridge_importance.sort_values(
    by="Absolute",
    ascending=False,
)

ridge_importance.drop(columns="Absolute")

             Feature  Coefficient
7                no2     5.448871
4               pm25     1.930174
19        pm25_lag_1    -1.636770
8                so2    -1.629913
2              month     1.615847
12          pressure     1.035093
10       temperature    -0.830617
14         aqi_lag_1     0.760330
13        wind_speed     0.463114
21       pm25_lag_24    -0.444951
25   aqi_roll_std_24     0.368890
18        aqi_lag_24     0.298428
22   aqi_roll_mean_6    -0.280449
1                day     0.220065
6                 o3     0.189997
11          humidity    -0.150009
15         aqi_lag_3    -0.117281
20        pm25_lag_6     0.086679
24  aqi_roll_mean_24    -0.082191
0               hour     0.080640
5               pm10    -0.058055
9                 co    -0.054845
16         aqi_lag_6     0.054391
17        aqi_lag_12     0.051770
23  aqi_roll_mean_12     0.022817
3        day_of_week    -0.017077

In [33]:
import joblib
import os

os.makedirs("../models", exist_ok=True)

joblib.dump(
    ridge_model,
    "../models/ridge_regression.pkl",
)
joblib.dump(lr_model, "../models/linear_regression_lag.pkl")
joblib.dump(rf_model, "../models/random_forest_lag.pkl")

print("Ridge Regression model saved successfully.")

Ridge Regression model saved successfully.

In [34]:
comparison = pd.DataFrame({
    "Model": [
        "Linear Regression",
        "Ridge Regression",
        "Random Forest",
    ],
    "MAE": [
        lr_mae,
        ridge_mae,
        rf_mae,
    ],
    "RMSE": [
        lr_rmse,
        ridge_rmse,
        rf_rmse,
    ],
    "R²": [
        lr_r2,
        ridge_r2,
        rf_r2,
    ],
})

comparison = comparison.sort_values(
    by="RMSE",
    ascending=True,
).reset_index(drop=True)

comparison

               Model        MAE       RMSE        R²
0      Random Forest   9.634611  12.665019  0.388539
1   Ridge Regression  13.276558  16.935405 -0.093322
2  Linear Regression  13.276649  16.935594 -0.093346

In [35]:
from xgboost import XGBRegressor

In [36]:
xgb_model = XGBRegressor(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    objective="reg:squarederror",
    random_state=42,
    n_jobs=-1,
)

xgb_model.fit(X_train, y_train)

print("XGBoost trained successfully.")

XGBoost trained successfully.

In [37]:
xgb_predictions = xgb_model.predict(X_test)

xgb_predictions[:10]

array([52.060474, 52.442688, 52.41382 , 52.32174 , 52.506187, 53.950905,
       54.14577 , 55.201515, 55.282352, 53.60365 ], dtype=float32)

In [38]:
xgb_mae = mean_absolute_error(y_test, xgb_predictions)

xgb_rmse = np.sqrt(mean_squared_error(y_test, xgb_predictions))

xgb_r2 = r2_score(y_test, xgb_predictions)

print(f"MAE  : {xgb_mae:.2f}")
print(f"RMSE : {xgb_rmse:.2f}")
print(f"R²   : {xgb_r2:.4f}")

MAE  : 8.88
RMSE : 11.85
R²   : 0.4644

In [39]:
xgb_importance = pd.DataFrame({
    "Feature": FEATURES,
    "Importance": xgb_model.feature_importances_,
})

xgb_importance = xgb_importance.sort_values(
    by="Importance",
    ascending=False,
)

xgb_importance

             Feature  Importance
9                 co    0.345610
4               pm25    0.129173
6                 o3    0.064467
2              month    0.060582
19        pm25_lag_1    0.057493
22   aqi_roll_mean_6    0.049385
5               pm10    0.044885
24  aqi_roll_mean_24    0.031128
8                so2    0.025460
1                day    0.022259
12          pressure    0.021664
21       pm25_lag_24    0.021632
23  aqi_roll_mean_12    0.018489
7                no2    0.018175
18        aqi_lag_24    0.014466
3        day_of_week    0.013359
25   aqi_roll_std_24    0.012592
14         aqi_lag_1    0.010347
17        aqi_lag_12    0.008027
20        pm25_lag_6    0.006506
11          humidity    0.006032
10       temperature    0.005429
13        wind_speed    0.005425
16         aqi_lag_6    0.003957
15         aqi_lag_3    0.002895
0               hour    0.000565

In [40]:
joblib.dump(
    xgb_model,
    "../models/xgboost.pkl",
)

print("XGBoost model saved successfully.")

XGBoost model saved successfully.

In [41]:
comparison = pd.DataFrame({
    "Model": [
        "Linear Regression",
        "Ridge Regression",
        "Random Forest",
        "XGBoost",
    ],
    "MAE": [
        lr_mae,
        ridge_mae,
        rf_mae,
        xgb_mae,
    ],
    "RMSE": [
        lr_rmse,
        ridge_rmse,
        rf_rmse,
        xgb_rmse,
    ],
    "R²": [
        lr_r2,
        ridge_r2,
        rf_r2,
        xgb_r2,
    ],
})

comparison = comparison.sort_values(
    by="RMSE",
    ascending=True,
).reset_index(drop=True)

comparison

               Model        MAE       RMSE        R²
0            XGBoost   8.876686  11.853086  0.464426
1      Random Forest   9.634611  12.665019  0.388539
2   Ridge Regression  13.276558  16.935405 -0.093322
3  Linear Regression  13.276649  16.935594 -0.093346

In [42]:
from lightgbm import LGBMRegressor

In [43]:
lgbm_model = LGBMRegressor(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
)

lgbm_model.fit(X_train, y_train)

print("LightGBM trained successfully.")

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.003295 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 5281
[LightGBM] [Info] Number of data points in the train set: 6720, number of used features: 26
[LightGBM] [Info] Start training from score 90.045970
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
LightGBM trained successfully.

In [44]:
lgbm_predictions = lgbm_model.predict(X_test)

lgbm_predictions[:10]

array([54.23363341, 54.07207167, 53.26770788, 53.06422684, 53.33742277,
       54.30832762, 53.78285748, 54.26358386, 54.5944777 , 52.50635818])

In [45]:
lgbm_mae = mean_absolute_error(y_test, lgbm_predictions)

lgbm_rmse = np.sqrt(mean_squared_error(y_test, lgbm_predictions))

lgbm_r2 = r2_score(y_test, lgbm_predictions)

print(f"MAE  : {lgbm_mae:.2f}")
print(f"RMSE : {lgbm_rmse:.2f}")
print(f"R²   : {lgbm_r2:.4f}")

MAE  : 9.01
RMSE : 12.17
R²   : 0.4353

In [46]:
lgbm_importance = pd.DataFrame({
    "Feature": FEATURES,
    "Importance": lgbm_model.feature_importances_,
})

lgbm_importance = lgbm_importance.sort_values(
    by="Importance",
    ascending=False,
)

lgbm_importance

             Feature  Importance
1                day        1057
2              month         561
9                 co         503
3        day_of_week         484
6                 o3         449
5               pm10         415
8                so2         403
24  aqi_roll_mean_24         391
12          pressure         388
25   aqi_roll_std_24         371
18        aqi_lag_24         306
17        aqi_lag_12         281
4               pm25         275
13        wind_speed         239
21       pm25_lag_24         229
23  aqi_roll_mean_12         209
10       temperature         197
11          humidity         172
7                no2         170
0               hour         141
16         aqi_lag_6         107
14         aqi_lag_1          91
22   aqi_roll_mean_6          89
20        pm25_lag_6          78
15         aqi_lag_3          76
19        pm25_lag_1          57

In [47]:
joblib.dump(
    lgbm_model,
    "../models/lightgbm.pkl",
)

print("LightGBM model saved successfully.")

LightGBM model saved successfully.

In [48]:
comparison = pd.DataFrame({
    "Model": [
        "Linear Regression",
        "Ridge Regression",
        "Random Forest",
        "XGBoost",
        "LightGBM",
    ],
    "MAE": [
        lr_mae,
        ridge_mae,
        rf_mae,
        xgb_mae,
        lgbm_mae,
    ],
    "RMSE": [
        lr_rmse,
        ridge_rmse,
        rf_rmse,
        xgb_rmse,
        lgbm_rmse,
    ],
    "R²": [
        lr_r2,
        ridge_r2,
        rf_r2,
        xgb_r2,
        lgbm_r2,
    ],
})

comparison = comparison.sort_values(
    by="RMSE",
    ascending=True,
).reset_index(drop=True)

comparison

               Model        MAE       RMSE        R²
0            XGBoost   8.876686  11.853086  0.464426
1           LightGBM   9.014308  12.171359  0.435278
2      Random Forest   9.634611  12.665019  0.388539
3   Ridge Regression  13.276558  16.935405 -0.093322
4  Linear Regression  13.276649  16.935594 -0.093346